version: "3.8"
services:
  app:
    build: .
    container_name: chat_app
    ports:
      - "8003:8002"
    depends_on:
      - mongo
      - postgres
    environment:
      - MONGO_URI=mongodb://mongo:27018
      - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/chatdb?sslmode=disable
    restart: always
  mongo:
    image: mongo:latest
    container_name: chat_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
  postgres:
    image: postgres:15
    container_name: chat_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1233456
      POSTGRES_DB: gotest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  websocket:
    build: ./web_socket_app
    container_name: chat_websocket
    ports:
      - "8004:8004"
    depends_on:
      - app
    restart: always

  frontend:
    build: ./chat-app
    container_name: chat_frontend
    ports:
      - "3000:3000"
    depends_on:
      - websocket
    restart: always

volumes:
  mongo_data:
  pgdata: