# version: "3.8"
# services:
#   app:
#     build: .
#     container_name: chat_app
#     ports:
#       - "8002:8002"  # Change if your app uses another port
#     depends_on:
#       - mongo
#       - postgres
#     environment:
#       - MONGO_URI=mongodb://mongo:27017
#       - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/chatdb?sslmode=disable
#     volumes:
#       - .:/app
#     restart: always
#   mongo:
#     image: mongo:latest
#     container_name: chat_mongo
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongo_data:/data/db
#     restart: always
#   postgres:
#     image: postgres:15
#     container_name: chat_postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123456
#       POSTGRES_DB: gotest
#     ports:
#       - "5432:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     restart: always
# volumes:
#   mongo_data:
#   pgdata:


version: "3.8"
services:
  app:
    build: .
    container_name: chat_app
    ports:
      - "8003:8002"
    depends_on:
      - mongo
      - postgres
    environment:
      - MONGO_URI=mongodb://mongo:27018
      - POSTGRES_URI=postgres://postgres:postgres@postgres:5432/chatdb?sslmode=disable
    restart: always
  mongo:
    image: mongo:latest
    container_name: chat_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always
  postgres:
    image: postgres:15
    container_name: chat_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1233456
      POSTGRES_DB: gotest
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  mongo_data:
  pgdata: